version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - config.env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - red_wordpress

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    env_file:
      - config.env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - red_wordpress
      
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_server
    privileged: true
    user: root
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        apt-get update && \
        apt-get install -y ca-certificates curl gnupg lsb-release && \
        install -m 0755 -d /etc/apt/keyrings && \
        curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
        chmod a+r /etc/apt/keyrings/docker.gpg && \
        echo "deb [arch=$$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $$(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list && \
        apt-get update && \
        apt-get install -y docker-ce-cli docker-compose-plugin && \
        exec /usr/local/bin/jenkins.sh
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.docker
volumes:
  db-data:
  wordpress_data:
  jenkins-data:

networks:
  red_wordpress:
    driver: bridge